# -*- mode: python ; coding: utf-8 -*-
#
# PyInstaller spec for Ducky Network & Security Tool
# Run via: build_installer.ps1  (do not run pyinstaller directly)

from PyInstaller.utils.hooks import collect_submodules, collect_data_files

# scapy and pysnmp use heavy dynamic imports — collect everything
scapy_hidden   = collect_submodules('scapy')
pysnmp_hidden  = collect_submodules('pysnmp')
pyasn1_hidden  = collect_submodules('pyasn1')

pysnmp_datas   = collect_data_files('pysnmp')
pyasn1_datas   = collect_data_files('pyasn1')

a = Analysis(
    ['src/ducky_app/main.py'],
    pathex=['src'],
    binaries=[],
    datas=[
        ('src/ducky_app/assets', 'ducky_app/assets'),
        *pysnmp_datas,
        *pyasn1_datas,
    ],
    hiddenimports=[
        *scapy_hidden,
        *pysnmp_hidden,
        *pyasn1_hidden,
        'telnetlib3',
        'zxcvbn',
        'serial',
        'psutil',
        'requests',
        'paramiko',
        'cryptography',
        'cryptography.hazmat.primitives',
        'cryptography.hazmat.primitives.ciphers',
        'cryptography.hazmat.backends',
        'cryptography.hazmat.backends.openssl',
        'PySide6.QtSvg',
        'PySide6.QtXml',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PyQt5',
        'PyQt6',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='Ducky',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,                          # no console window for GUI app
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='src\\ducky_app\\assets\\ducky_icon.ico',   # generated by build_installer.ps1
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Ducky',
)
